### PR TITLE
Removed deprecated API

### PR DESCRIPTION
**Pull request by pablochacin**
Remove from the extension the deprecated API.

Signed-off-by: Pablo Chacin <pablochacin@gmail.com>

### CODE REVIEW

**Comment by javaducky** [comment]
This should NOT be merged until folks have the warning and time to update their scripts.

**Comment by pablochacin** [comment]
@javaducky I agree some example scripts may be useful, but the bulk just show how to use the API and I think those have little value. Have you identified some you consider more useful?

**Comment by javaducky** [comment]
@pablochacin, just from a quick review, things like `apply-deployment-service-ingress.js`, `add-ephemeral.js`, `create-job.js`, `create-job-by-nodename.js`, to name a few. These are more than simple CRUD examples. 

I realize that many of these may overlap with things you're adding with the [xk6-disruptor](https://github.com/grafana/xk6-disruptor) project, but we should not _force_ folks to include yet another extension if their needs don't require it, so leaving them an example would be nice. As the person wishing to remove these existing scripts, _you_ should justify why they are not necessary. I feel this was originally a simple global delete.

**Comment by pablochacin** [comment]
@javaducky The problem I see with some examples, such as `create-job-by-nodename.js` is that they rely on the functionality we are removing. Eventually we could re-introduce some of these functions as helpers (I think creating a job in node is a good candidate for such helper) and then we would provide the required example.

With respect of other cases such as `create-job.js` But, given that we are basically allowing users to use yaml manifests for creating any resources, I don't see how these examples add value, we can simply point to the proper Kubernetes documentation. 

With respect of the `add-ephemeral.js` as per [this issue,](https://github.com/grafana/xk6-kubernetes/issues/66) we should remove these functionality from the `xk6-kubernetes` because it is too specialized and makes sense only in the context of the `xk6-disruptor`.

**Pull request closed without merging**
